name: Metrics
on:
  # Schedule weekly updates
  schedule: [{cron: "1/30 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: 
    branches:
      - "master"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ALL_ACCESS_TOKEN }}
          
          #Options?
          user: yuange86
          template: classic
          
          base: header, activity, community, repositories, metadata
          
          
          
