name: Metrics
on:
  # Schedule weekly updates
  schedule: [{cron: "0 0 5/7 * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          
          #Options?
          user: yuange86
          template: classic
          repositories_forks: on
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Seoul
          config_twemoji: on
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 10
          plugin_activity_load: 200
          plugin_activity_timestamps: yes
          plugin_activity_visibility: public
          plugin_calendar: yes
          plugin_discussions: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 31
          plugin_habits_facts: yes
          plugin_habits_from: 250
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 0
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 31
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_projects: yes
          plugin_projects_descriptions: yes
          plugin_projects_limit: 4
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot]
          plugin_reactions_limit: 250
          plugin_reactions_limit_issues: 100
          plugin_repositories: yes
          plugin_repositories_featured: yuange86/DevKa, yuange86/heaven-world, yuange86/eller-time-bot, yuange86/ONC-E-
          plugin_stargazers: yes
          plugin_stars: yes
          plugin_stars_limit: 10
          plugin_traffic: yes
